#FeatherMorph plugin options
root:

  # The message pattern used for this plugin to display messages for players
  message_pattern: <color:#dddddd>≡ FM » <message>

  # Should we check updates automatically?
  check_update: true

  # Allow players acquire morphs by killing mobs and other players?
  allow_acquire_morphs: true

  # Allow players to fly if they disguised as a mob that can fly?
  allow_flight: true

  # Should we check whether a player has the permission to activate a ability?
  check_ability_permissions: true

  # Disguise as the id given below when they join the server.
  # If an invalid ID is provided, this option may not take place.
  forced_disguise: "@none"

  # Modify mobs' AI to make them react to disguises?
  #
  # PS: !!!This option requires a server restart to make changes!!!
  # PS: Also, it's not recommended to reload the server after disabling this option.
  #     While we try to undo changes it made, the mobs' behavior will still have distinction compared to vanilla
  modify_ai: true

  # The GUI pattern for the fallback disguise selection.
  # It's a bit limited
  #
  # Available widgets:
  #   D: The available disguise to select
  #   C: The current disguise [1]
  #   U: "Undisguise" button. [1]
  #   P: "Last page" button. [1]
  #   N: "Next page" button [1]
  #   x: The border (Pink stained glass pane)
  # Note:
  #   [1]:  This widget will turn black when unavailable.
  #         If you wish to make them display as the border, replace it with the small cap variant.
  gui_pattern:
    - "Cxxxxxxxx"
    - "DDDDDDDDD"
    - "DDDDDDDDD"
    - "DDDDDDDDD"
    - "PPPuuuNNN"

  # ChatOverride options
  chatOverride:
    # Enable ChatOverride?
    # Once enabled, we will attempt to change someone's chat message to a configured content if they disguised as something.
    # The "morph:chat_override" ability needs to be added to disguise's abilities to activate this feature.
    allowOverride: false

    # Should we try to override any existing chat plugin?
    # This will make sure that the player's name can be changed in most situations but may cause compatibility issues.
    UseCustomRenderer: true

    # The default pattern for ChatOverride
    default_pattern: <<who>> <message>

  # Language options
  language:
    # Sets the default language for the plugin
    # This will affect most ingame messages and bossbar title
    code: en_us

    # Enable single-language mode?
    # Once enabled, all ingame messages will be forced to use the default language.
    # Otherwise, we will send ingame messages depending on which language the player uses.
    # Some features may not be affected by this option.
    single_language: false

  # Should we enable the "Disguise Revealing" feature?
  #
  # This was made to nerf the ability for players to not get targeted by hostile mobs.
  # Once enabled, they will get "revealed" to mobs and lose the ability to ignore by mobs, if they make too many actions.
  #
  # Requires client integration
  #
  # For more information, please check: https://modrinth.com/plugin/feathermorph/version/0.12.3-1
  revealing: true

  # Skill cooldown on damage.
  # Defines how many ticks should a player wait at least before they activate the skill again when they get damaged.
  cooldown_on_damage: 15

  # Bounding box options
  bounding_boxes:
    # Modify players' bounding box depending on their disguise?
    # Experimental feature, slight glitches may occur when flying around.
    # Incompatible with anti-cheats!
    modify_boxes: false

    # Should we check if there is enough space to disguise?
    check_space: true

  # Should we make Armor Stand disguises show arms by default?
  armorstand_show_arms: true

  # Should players undisguise themselves on death?
  unmorph_on_death: true

  # Should we allow players to disguise themselves by using skulls/heads?
  allowHeadMorph: true

  # Should piglin brutes ignore players' disguises?
  piglin_brute_ignore_disguises: true

  # (EXPERIMENTAL) Should we hide disguised players from the TAB list?
  # Note that if there's some other plugin that operates the TAB list, this feature may not work as expected
  # Also this will cause problems with chat signing, you may want to disable it first.
  hide_disguised_players_in_tab: false

  # Server renderer options
  server_renderer:
    # (EXPERIMENTAL) Should we show player disguises in the TAB list?
    show_player_disguises_in_tab: false

  # Health scale options
  health_scale:
    # Enable health scale?
    # Once enabled, we will attempt to scale players' base health depending on their disguise type.
    # Only affects vanilla disguises.
    enabled: true

    # Maximum base health
    # We will try to cap the player's base health to the configured value if they exceed it.
    max_health: 60

  # Bossbar options
  bossbar:
    # Should we display bossbars to players?
    # Disable this will also disable the bossbar ability for all disguises.
    enabled: true

  # Fly ability options
  flying:
    # The base distance for Hunger consumption.
    # Players' Hunger will drop one level (Half of a drumstick) once they have traveled this far.
    exhaustion_base: 200

    # Add a minimal consumption limit (20% of the configured consumption speed) as an "Idle consumption" for players per tick.
    idle_consumption: true

    # Prevent players from flying in water in these worlds
    #
    # Example:
    # disallow_in_water:
    #   - example_world1
    #   - example_world2
    disallow_in_water:
      - example_world1
      - example_world2

    # Prevent players from flying in lava in these worlds
    #
    # We HIGHLY suggest adding nether worlds to this list, since there are mods that can remove the fog in lava
    # This can prevent players from mining Ancient Debris under lava in nether using the fly ability
    #
    # Example:
    # disallow_in_lava:
    #   - example_world1
    #   - example_world2
    disallow_in_lava:
      - example_world1
      - example_world2

  # Disable Fly Ability in the following worlds
  #
  # Example:
  # nofly_worlds:
  #   - example_world1
  #   - example_world2
  nofly_worlds:
    - example_world1
    - example_world2

  # Ambient sound options
  ambient_sounds:
    # The frequency for this plugin to play ambient sounds for disguises.
    # Set to 0 to disable
    frequency: 1.0

  # InteractionMirror options
  # This is a feature that's made for fun, it could make another player do the same thing as you did when disguising as them
  # Disabled for default since 1.0.15
  interactionMirror:
    # Maximum affect distance
    # How far should we find for the target player to mirror?
    # Set to 0 to disable this feature, or -1 to disable the limit.
    normalDistance: -1

    # Should we ignore disguised players when finding a target?
    ignore_disguised: true

    # Block destroy timeout
    # How many ticks should we wait to reset progress when simulating block destroy if there's no operation?
    # Values that are too small may cause the progress to reset repeatedly with a bad network.
    destroy_timeout: 20

    # Selection mode
    # How should we search for the target player to mirror?
    # by_name: Search for the specific player who matches our disguised name.
    # by_sight: Search for the nearest player who matches our disguise target within 5 blocks in sight.
    #           A player disguised as our target can also be selected.
    selection_mode: by_name

    # Log operations
    # Should we log any InteractionMirror operations performed by players?
    # Logs can be found in mirror_history.log
    log_operations: false

    # Delete logs that are older than the configured days
    # Set to 0 to disable this feature.
    log_cleanup: 7

    # Behavior options
    behaviors:
      # Should we enable interaction control?
      simulate_interactions: false

      # Should we enable sneaking control?
      sneak: false

      # Should we enable swapping control?
      swap_hands: false

      # Should we enable drop control?
      allow_drop: false

      # Should we enable hotbar control?
      hotbar: false

  # Banned disguises
  # Disguises in this list won't be available in-game for anyone.w
  #
  # Use '@default' to disable all disguises under a category, like 'player:@default' or 'minecraft:@default'
  # Remember to add quotes or the library we use to read the config will panic ;)
  #
  # Example:
  # bannedDisguises:
  #   - minecraft:example_mc_disguise
  #   - player:a_player_disguise
  #   - 'foo:@default'
  bannedDisguises:
    - minecraft:example_mc_disguise
    - player:a_player_disguise
    - 'foo:@default'

  # Client integration options
  client:
    # Should we allow client integrations?
    allow_client_mod: true

    # Should we log packets coming from the client?
    log_incoming_packets: false

    # Should we kick players if their client mod doesn't match our API version?
    #
    # Note: This only checks the player who joined with the client mod.
    #       Players may have their mod implementing our API, so don't treat this as an anti-cheat feature.
    force_version: false

    # Should we log packets sent to the client?
    log_outgoing_packets: false

    # Make clients render other players' disguises when LibsDisguises is not present?
    # Requires the client to implement the v11 protocol
    client_renderer: true

  # Multi instance network options
  # This network is used to sync the player data across multiple FeatherMorph instances
  multi_instance:
    # Enable this feature?
    enabled: false

    # The address where the master server is.
    # If `is_master_service` is on, this will be the address we open the service at.
    master_address: "0.0.0.0:39210"

    # Whether we are the master server in the instance network or not
    is_master_service: false

    # The secret token for the network
    # DO NOT SHARE THIS TO OTHERS! OR ANYONE WITH THE SECRET WILL BE ABLE TO CONNECT TO THE INSTANCE NETWORK!
    secret: "~UNSET"

  # NBT blacklist options
  # Defines tags that should not be sent to the client when syncing disguise states.
  nbt_blacklist:
    # Patterns
    # Any tag that matches one of these patterns will not send to the client.
    patterns:
      - '[pP]urpur.*'
      - '[pP]aper.*'
      - '[sS]pigot.*'
      - '[bB]ukkit.*'
      - Xp.*
      - food.*
      - Death.*
      - Spawn.*

    # Names
    # Any tag with one of these names in this list will not send to the client.
    names:
      - UUID
      - data
      - Brain
      - Motion
      - palette
      - Attributes
      - Invulnerable
      - DisabledSlots
      - ArmorItems
      - HandItems
      - Tags
      - recipes
      - Inventory
      - abilities
      - recipeBook
      - EnderItems
      - warden_spawn_tracker
      - previousPlayerGameType
      - LastDeathLocation
      - playerGameType
      - seenCredits
      - Score
      - Offers
      - LastRestock
      - RestocksToday
      - Pos
      - Owner
      - WorldUUIDLeast
      - WorldUUIDMost
      - Rotation
      - listener
      - ActiveEffects
      - ArmorDropChances
      - PersistenceRequired
      - SelectedItem

  # Do not touch unless you know what you're doing!
  version: 37
