root:
  # 聊天覆盖：某个玩家发言后是否要将消息显示为其伪装的玩家所发出？
  # 在公开服务器上启用此功能可能会导致非常不妙的事情吧...
  chatOverride:
    # 启用、禁用功能
    allowOverride: false
    # 是否使用自定义消息格式？
    UseCustomRenderer: true

  # 语言
  language:
    # 服务器语言
    # 将影响控制台输出、Bossbar名称以及本地化fallback过程
    code: zh_cn

    # 是否启用单语言模式？
    # 启用后将强制使用服务器设定的语言配置
    single_language: false

  # 收到伤害时的技能CD
  # 玩家受到伤害后技能CD将至少为下面配置的时间（单位：游戏刻）
  cooldown_on_damage: 15

  # 技能物品
  # 玩家使用技能、快速伪装、取消伪装时需要手持的物品
  # 设置为"disabled"以禁用
  action_item: minecraft:carrot_on_a_stick

  # 盔甲架伪装是否要默认附加手臂？
  armorstand_show_arms: true

  # 是否要在玩家死亡时取消他们的伪装？
  unmorph_on_death: true

  # 是否允许通过头颅进行伪装？
  allowHeadMorph: true

  # 猪灵蛮兵是否要忽略伪装？
  piglin_brute_ignore_disguises: true

  # 生命值缩放
  health_scale:
    # 是否启用此功能？
    enabled: true
    # 缩放的最大生命值
    max_health: 60

  # 是否允许使用LibsDisguises的本地伪装
  # PS: 本地伪装就是你通过`/savedisg`保存的伪装
  # PS: 因为API限制，快速伪装无法识别某人的伪装是否为自定义伪装，
  #     这可能会导致复制的伪装不完整
  enable_ld_custom_disguises: false

  bossbar:
    # 是否允许显示Bossbar?
    enabled: true

  reverseControl:
    # 反向控制距离：当某个人变成其他玩家时，距离多少格可以控制被伪装玩家的一些动作？
    # 设置为0可以禁用某一功能，设置为-1则无距离限制
    # 正常距离
    normalDistance: -1
    # 免疫距离（佩戴特定物品时的可控制距离）
    immuneDistance: 16
    # 免疫物品（当被伪装玩家佩戴此物品时将使用上方配置的距离检查）
    immuneItem: minecraft:golden_helmet
    # 目标玩家伪装时是否忽略？
    ignore_disguised: true
    # 模拟方块摧毁时，要经过多久没操作再重置摧毁进度？（单位：游戏刻）
    # 太小的值可能在延迟或网络不稳定时导致进度被频繁重置
    destroy_timeout: 20
    # 行为：开启或禁用某一功能的镜像
    # 聊天覆盖在上方"chatOverride"中
    behaviors:
      # 是否要模拟操作？
      simulate_interactions: true
      # 是否同步下蹲？
      sneak: false
      # 是否同步副手切换？
      swap_hands: false
      # 是否允许丢弃物品？
      allow_drop: false
      # 是否允许同步已选Hotbar槽？
      hotbar: false

  # 已禁用的伪装，此列表里的伪装将不会对玩家可用，例如：
  # bannedDisguises:
  # - "minecraft:allay"
  # - "player:dinnerbone"
  bannedDisguises: []

  # 客户端集成选项
  client:
    # 是否允许客户端集成？
    allow_client_mod: true
    # 是否记录客户端发来的包？
    log_incoming_packets: false
    # 是否记录发送给客户端的包？
    log_outgoing_packets: false

  # 不要动这个键!
  version: 13
