root:
  # 聊天覆盖：某个玩家发言后是否要将消息显示为其伪装的玩家所发出？
  # 在公开服务器上启用此功能可能会导致非常不妙的事情吧...
  chatOverride:
    # 启用、禁用功能
    allowOverride: false
    # 是否使用自定义消息格式？
    UseCustomRenderer: true

  # 语言
  language:
    # 目标Minecraft语言
    # 目前只支持向玩家发送对应语言的生物名称
    code: zh_cn

    # 如果没有语言可用，是否要转换为translatable让客户端自行翻译？
    # 注：translatable和消息中的“<rainbow>”、“<gradient>”不兼容
    cast_translatable: true

  # 收到伤害时的技能CD
  # 玩家受到伤害后技能CD将至少为下面配置的时间（单位：游戏刻）
  cooldown_on_damage: 15

  # 技能物品
  # 玩家使用技能、快速伪装、取消伪装时需要手持的物品
  # 设置为"disabled"以禁用
  action_item: minecraft:carrot_on_a_stick

  # 是否允许用玩家头快速伪装？
  allowHeadMorph: true

  # 是否允许使用LibsDisguises中的自定义伪装？
  # 注：因为API限制，快速伪装无法识别某人的伪装是否为自定义伪装，
  #    这可能会导致复制的伪装不完整
  enable_ld_custom_disguises: false

  bossbar:
    # 是否要为Boss伪装启用Bossbar?
    enabled: true
    # Bossbar显示范围，小于0则是 (服务器视距 - 1) * 16 格
    range: -1

  reverseControl:
    # 反向控制距离：当某个人变成其他玩家时，距离多少格可以控制被伪装玩家的一些动作？
    # 设置为0可以禁用某一功能，设置为-1则无距离限制
    # 正常距离
    normalDistance: -1
    # 免疫距离（佩戴特定物品时的可控制距离）
    immuneDistance: 16
    # 免疫物品（当被伪装玩家佩戴此物品时将使用上方配置的距离检查）
    immuneItem: minecraft:golden_helmet
    # 目标玩家伪装时是否忽略？
    ignore_disguised: true
    # 行为：开启或禁用反向控制的某一功能
    # 聊天覆盖在上方"chatOverride"中
    behaviors:
      # 是否要模拟右键？
      simulate_interactions: true
      # 是否要同步挥手？
      swing_hands: true
      # 是否同步下蹲？
      sneak: false
      # 是否同步副手切换？
      swap_hands: false
      # 是否允许丢弃物品？
      allow_drop: false
      # 是否允许同步已选Hotbar槽？
      hotbar: false

  # 已禁用的伪装，此列表里的伪装将不会对玩家可用，例如：
  # bannedDisguises:
  # - "minecraft:allay"
  # - "player:dinnerbone"
  bannedDisguises: []

  # 不要动这个键!
  version: 8
